### ISSUE TITLE
Handle accessing with question_id that doesn't exist via path 

### ISSUE THREAD

**Issue by ThanadolU** [thanidacwn/ku-polls#58]
It give me internal server 500
<img width="293" alt="image" src="https://github.com/thanidacwn/ku-polls/assets/90590580/1142d88f-ac16-482a-9090-95f3a05f825e">
I recommend you redirect it to index page and show message that warns the user.

**Comment by thanidacwn** [comment]
already fixed it, Now it's redirect to index page if question_id that doesn't exist and show error message.
